### ISSUE TITLE
CPU Spike while instrumenting application in container environment

### ISSUE THREAD

**Issue by WassimDhib** [elastic/apm-agent-java#1902]
Hi

When I instrument a a java application running in container 

`/bin/java -XX:+UseG1GC -jar /tmp/apm-agent-attach.jar --config config_file=/tmp/elasticapm.properties  --pid $pid_java`

I see a spike in CPU usage, and my container gets killed when it hits the CPU limit

Is there a way to reduce CPU consumption or to flatten the curve (even if it goes slowly)

![image](https://user-images.githubusercontent.com/30473593/124575273-8cbc5b80-de4b-11eb-8afb-a24f6ade7a81.png)

**Comment by jackshirazi** [comment]
why exactly is the container killed? CPU is a compressible resource and the container gets throttled, it's only killed on an OOM

**Comment by eyalkoren** [comment]
If you are not using agent 1.24.0, try upgrading to it. It included a fix for our type pool cache that may be related.

**Comment by WassimDhib** [comment]
> 
> 
> why exactly is the container killed? CPU is a compressible resource and the container gets throttled, it's only killed on an OOM

I've got an "exit code 137"

This is my container configuration 

```yaml
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 2Gi
```
