### ISSUE TITLE
Testing Agent attach with Fleet

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-java#2196]

**Comment by eyalkoren** [comment]
## Stage I - integration between APM Server and the agent cli
Testing APM Server 8.x with a config such as:
```yml
  java_attacher:
    enabled: true
    download-agent-version: 1.27.1
    discovery-rules:
    - include-main: opbeans
    - exclude-main: ".*"
    config:
      server_url: "<MY-APM-SERVER-URL>"
      secret_token: "XXXXXXXXXXXXXXXX"
```
- [x] test with `enabled: true/false`
- [x] test `download-agent-version` with multiple versions
- [x] test `include-user` and `exclude-user`
- [x] test `include-main` and `exclude-main`
- [x] test with `include-vmargs: "elastic.apm.attach=true"`

## Stage II - end-to-end testing through Fleet integrations UI
- [ ] test `download-agent-version` with multiple versions
- [ ] test `include-user` and `exclude-user`
- [ ] test `include-main` and `exclude-main`
- [ ] test attachment with the default rule `include-vmargs: "elastic.apm.attach=true"`
