### ISSUE TITLE
Incorrect containerID detection in apm-java-agent on GKE Autopilot cluster

### ISSUE THREAD

**Issue by b2ronn** [elastic/apm-agent-java#3510]
**Description:**
The apm-java-agent seems to incorrectly determine the containerID when the application is running on a GKE Autopilot cluster. This issue leads to discrepancies between the actual containerID (and other related identifiers like pod name/pod UID) and those obtained by collected via elastic-agent (https://www.elastic.co/blog/elastic-observe-gke-autopilot-clusters).

**Steps to Reproduce:**
Deploy an application utilizing the apm-java-agent on a GKE Autopilot cluster.
Check  /proc/self/cgroup and /proc/self/mountinfo.

```
root@petclinic-ecs-674d54744b-7vbpf:/# cat /proc/self/cgroup
0::/

root@petclinic-ecs-674d54744b-7vbpf:/# cat /proc/self/mountinfo
7253 5454 0:767 / / rw,relatime master:1694 - overlay overlay rw,lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.gcfs/snapshotter/snapshots/723/fs:/var/lib/containerd/io.containerd.snapshotter.v1.gcfs/snapshotter/snapshots/722/fs:/var/lib/containerd/io.containerd.snapshotter.v1.gcfs/snapshotter/snapshots/721/fs:/var/lib/containerd/io.containerd.sn
apshotter.v1.gcfs/snapshotter/snapshots/720/fs,upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.gcfs/snapshotter/snapshots/741/fs,workdir=/var/lib/containerd/io.containerd.snapshotter.v1.gcfs/snapshotter/snapshots/741/work
7254 7253 0:769 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
7255 7253 0:777 / /dev rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
7256 7255 0:778 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666
7257 7255 0:703 / /dev/mqueue rw,nosuid,nodev,noexec,relatime - mqueue mqueue rw
7258 7253 0:763 / /sys ro,nosuid,nodev,noexec,relatime - sysfs sysfs ro
7259 7258 0:25 / /sys/fs/cgroup ro,nosuid,nodev,noexec,relatime - cgroup2 cgroup rw
7260 7253 8:1 /var/lib/kubelet/pods/2273539b-7ec7-4467-a054-2d3281d70f50/etc-hosts /etc/hosts rw,relatime - ext4 /dev/sda1 rw,commit=30
7261 7255 8:1 /var/lib/kubelet/pods/2273539b-7ec7-4467-a054-2d3281d70f50/containers/petclinic-ecs/371ec6a4 /dev/termination-log rw,relatime - ext4 /dev/sda1 rw,commit=30
7262 7253 8:1 /var/lib/containerd/io.containerd.grpc.v1.cri/sandboxes/1e4ea4f01f1ccb5d8cd20fc0b818c3e308c99df78efdaa6de2c283f013033a0d/hostname /etc/hostname rw,nosuid,nodev,relatime - ext4 /dev/sda1 rw,commit=30
7263 7253 8:1 /var/lib/containerd/io.containerd.grpc.v1.cri/sandboxes/1e4ea4f01f1ccb5d8cd20fc0b818c3e308c99df78efdaa6de2c283f013033a0d/resolv.conf /etc/resolv.conf rw,nosuid,nodev,relatime - ext4 /dev/sda1 rw,commit=30
7264 7255 0:613 / /dev/shm rw,nosuid,nodev,noexec,relatime - tmpfs shm rw,size=65536k
7265 7253 8:1 /var/lib/kubelet/pods/2273539b-7ec7-4467-a054-2d3281d70f50/volumes/kubernetes.io~empty-dir/elastic-apm-agent /elastic/apm/agent rw,relatime - ext4 /dev/sda1 rw,commit=30
7266 7253 0:612 / /run/secrets/kubernetes.io/serviceaccount ro,relatime - tmpfs tmpfs rw,size=2097152k
5455 7254 0:769 /bus /proc/bus ro,nosuid,nodev,noexec,relatime - proc proc rw
5456 7254 0:769 /fs /proc/fs ro,nosuid,nodev,noexec,relatime - proc proc rw
5457 7254 0:769 /irq /proc/irq ro,nosuid,nodev,noexec,relatime - proc proc rw
5458 7254 0:769 /sys /proc/sys ro,nosuid,nodev,noexec,relatime - proc proc rw
5459 7254 0:769 /sysrq-trigger /proc/sysrq-trigger ro,nosuid,nodev,noexec,relatime - proc proc rw
5460 7254 0:779 / /proc/acpi ro,relatime - tmpfs tmpfs ro
5461 7254 0:777 /null /proc/kcore rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
5462 7254 0:777 /null /proc/keys rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
5463 7254 0:777 /null /proc/timer_list rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
5464 7254 0:780 / /proc/scsi ro,relatime - tmpfs tmpfs ro
5465 7258 0:781 / /sys/firmware ro,relatime - tmpfs tmpfs ro
root@petclinic-ecs-674d54744b-7vbpf:/#
```

and pod status
```
status:
  initContainerStatuses:
    - name: elastic-java-agent
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2024-01-30T15:31:38Z'
          finishedAt: '2024-01-30T15:31:38Z'
          containerID: >-
            containerd://47948ded77336c7b2bf16cf5976834ddc8b42bde7adec06a9b700b78dc917f2e
      lastState: {}
      ready: true
      restartCount: 0
      image: docker.elastic.co/observability/apm-agent-java:latest
      imageID: >-
        docker.elastic.co/observability/apm-agent-java@sha256:fbe7c86ef814626ba52b5efed4a7101d12eef86ad05b9108b39c23f32eadd6d6
      containerID: >-
        containerd://47948ded77336c7b2bf16cf5976834ddc8b42bde7adec06a9b700b78dc917f2e
  containerStatuses:
    - name: petclinic-ecs
      state:
        running:
          startedAt: '2024-01-30T15:31:40Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: ghcr.io/pavolloffay/spring-petclinic:latest
      imageID: >-
        ghcr.io/pavolloffay/spring-petclinic@sha256:83954b8b893bc010071ffc82db60262dd4b8d1b410f29174abf0926e7c27de4e
      containerID: >-
        containerd://c9e786202e41b88d91a5ef1997cf6a0751aa3c4b3d3fcbcc4cc7e7418402b787
      started: true
  qosClass: Guaranteed
```

Compare the obtained containerID with the one reported in the status.

<details>
  <summary>Click to open Example Deployment</summary>
```
<pre>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-ecs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: petclinic-ecs
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: petclinic-ecs
    spec:
      volumes:
        - name: elastic-apm-agent
          emptyDir: {}
      initContainers:
        - name: elastic-java-agent
          image: docker.elastic.co/observability/apm-agent-java:latest
          command:
            - cp
            - '-v'
            - /usr/agent/elastic-apm-agent.jar
            - /elastic/apm/agent
          volumeMounts:
            - name: elastic-apm-agent
              mountPath: /elastic/apm/agent
      containers:
        - name: petclinic-ecs
          image: ghcr.io/pavolloffay/spring-petclinic:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: KUBERNETES_POD_UID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.uid
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: ELASTIC_APM_SERVICE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.uid
            - name: ELASTIC_APM_SERVER_URL
              value: https://APMSERVER
            - name: ELASTIC_APM_SERVICE_NAME
              value: petclinic-ecs
            - name: ELASTIC_APM_APPLICATION_PACKAGES
              value: org.springframework.samples.petclinic
            - name: ELASTIC_APM_ENVIRONMENT
              value: dev
            - name: ELASTIC_APM_LOG_ECS_REFORMATTING
              value: OVERRIDE
            - name: JAVA_TOOL_OPTIONS
              value: '-javaagent:/elastic/apm/agent/elastic-apm-agent.jar'
            - name: ELASTIC_APM_GLOBAL_LABELS
              value: some=labels
          volumeMounts:
            - name: elastic-apm-agent
              mountPath: /elastic/apm/agent
</pre>
```
</details>

PS: and it would be good to define Pod_Name(as example from /etc/hostname)/Pod_UID/Node_Name from inside the container, without env variables.
